# Generated by Django 5.1.7 on 2025-03-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrepreneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('expertise', models.CharField(max_length=200)),
                ('image', models.URLField()),
                ('industry', models.CharField(max_length=100)),
            ],
        ),
    ]
